### ISSUE TITLE
Question about freezing backbone and Linking tokens to instances

### ISSUE THREAD

**Issue by ByeongHyunPak** [w1oves/Rein#1]
Hi, I'm interested in your impressive work!
And I have a question about freezing backbone and Linking tokens to instances.

1. Where is the code for freezing the backbone?
2. Is it correct that the token is linked to the decoder's query during training?
    - In the released code, token appears to be linked only once for the first time. 

            if use_rein:

                    ...

                    self.head.load_state_dict(head_state, strict=False)

                    self.head.link(self.backbone.rein.link_to_querys())

Thank you :)

**Comment by w1oves** [comment]
Hello! Thank you for your interest in my work. Regarding your questions, here are my responses:

1. The code to freeze the backbone is straightforward. I achieve this by modifying the model's `train()` method and only adding the parameters that need training when constructing the optimizer. This repository contains only Rein's architecture and inference code. As the paper is currently in the submission process, I am considering when to organize and release Rein's training code. If you urgently need the training code now, please contact my email at zhixiangwei@mail.ustc.edu.cn.

2. During the testing phase, the `link_to_query` function indeed only needs to be executed once. For each iteration in the training phase, new queries are generated by executing the `link_to_query` function.
