### ISSUE TITLE
Error about demo.ipynb

### ISSUE THREAD

**Issue by SuiyvSYC** [w1oves/Rein#19]
/home/XXX/moe_seg/moe_exp_seg/pytorch_seg/Rein/rein/models/backbones/dino_layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/XXX/moe_seg/moe_exp_seg/pytorch_seg/Rein/rein/models/backbones/dino_layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/XXX/moe_seg/moe_exp_seg/pytorch_seg/Rein/rein/models/backbones/dino_layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
Loads checkpoint by local backend from path: checkpoints/dinov2_segmentor.pth
/home/XXX/anaconda3/envs/rein/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343970094/work/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/XXX/anaconda3/envs/rein/lib/python3.11/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
  
  The code is no longer running at this stage and the model is successfully loaded onto the gpu

**Comment by SuiyvSYC** [comment]
My running environment：
mmcv            2.1.0      https://github.com/open-mmlab/mmcv
mmdet           3.3.0      https://github.com/open-mmlab/mmdetection
mmengine        0.10.3     https://github.com/open-mmlab/mmengine
mmpretrain      1.2.0      https://github.com/open-mmlab/mmpretrain
mmsegmentation  1.2.2      https://github.com/open-mmlab/mmsegmentation
Training and testing are running normally

**Comment by SuiyvSYC** [comment]
vis_img=show_result_pyplot(network,im_path,result,wait_time=1)
there is something changed  in this function，because ”wait_time“ param 

wait_time (float): The interval of show (s). 0 is the special value that means "forever". Defaults to 0.
so we can change it to solve the problem

**Comment by w1oves** [comment]
Ok, Thank you.
