### ISSUE TITLE
Question about full fine tuning exp. results

### ISSUE THREAD

**Issue by ByeongHyunPak** [w1oves/Rein#2]
Hi, I'm interested in your impressive work!
And I have a question about full fine tuning experiment results.

How many iterations did you train full fine tuning method?
In my experience, [EVA-02+ Mask2Former] is sufficiently saturated in 5k iterations.

Thank you :)

**Comment by w1oves** [comment]
Our training process is as described in the implementation details of the Experiments section of our paper. To maintain consistency with other experiments, we trained for 40K iterations on the GTAV->Cityscapes configuration. To validate your question, we tested checkpoints at intervals of 8K iterations during the training process for their performance on the Cityscapes validation set and plotted the mIoU curves. Thank you for your valuable suggestion!
![8e88fd5a4bf2144f53bbf404c6d809a](https://github.com/w1oves/Rein/assets/54713447/4f47fd9e-7209-4653-80d0-67f0ca3537a1)
