### ISSUE TITLE
Cityscapes best model weights

### ISSUE THREAD

**Issue by amundra15** [w1oves/Rein#20]
Hi,

Thanks for releasing this amazing work. I noticed that the best-performing model on cityscapes ("+1/16 of Cityscapes training Cityscapes") isn't available. Could you please release the weights of that model too?

Best,
Akshay

**Comment by w1oves** [comment]
Yes, I can. It will be available at tomorrow.

**Comment by w1oves** [comment]
https://github.com/w1oves/Rein/releases/tag/Semi-Supervised(1%2F16)
