### ISSUE TITLE
How to visualize and save the segmentation results

### ISSUE THREAD

**Issue by seabearlmx** [w1oves/Rein#22]
Hello, how to visualize and save the segmentation results?

**Comment by w1oves** [comment]
* **Visualization:** To visualize, use `tools/test.py` with the `--show` option.
* **Saving Color Map:** Save the color map by running `tools/test.py` with the `--show-dir` option.
* **Saving Label Map for Submission:** Use `tools/test.py` to save the label map for submission. Set `format_only=True` and `output_dir=\path\to\your` in `test_evaluator`.
* Detailed instructions can be found at [this link](https://mmsegmentation.readthedocs.io/en/latest/user_guides/4_train_test.html).
