### ISSUE TITLE
About GTA5+SYNTHIA config file

### ISSUE THREAD

**Issue by seabearlmx** [w1oves/Rein#23]
Hello, how to config the GTA5+SYNTHIA? In Release/source code/Rein-GTAV-Synthia/config/base/dataset/ your provided, I have not found the dg_gta_syn_xx.py config file. I try to set the config:

train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=False,
    pin_memory=False,
    sampler=dict(type="InfiniteSampler", shuffle=True),
    dataset=dict(
        type="ConcatDataset",
        datasets=[
            {{_base_.train_gta}},
            {{_base_.train_syn}}
        ],
    ),
)

but it work failed.

**Comment by w1oves** [comment]
This [config](https://github.com/w1oves/Rein/releases/download/GTAV%2BSynthia/config.py) file in  [release](https://github.com/w1oves/Rein/releases/tag/GTAV%2BSynthia) is used for DG (Domain Generalization) settings, specifically converting GTAV+Synthia to Cityscapes+Bdd100k+Mapillary. You can verify this by examining the `train_dataloader` and `val_dataloader` within the file. Additionally, feel free to make direct modifications as needed.

**Comment by seabearlmx** [comment]
However, I follow the config file to modify, the error happens: TypeError: ConcatDataset.__init__() got an unexpected keyword argument 'pipeline'

**Comment by w1oves** [comment]
Please provide your modified config.

**Comment by seabearlmx** [comment]
```
_base_ = [
    "./gta_512x512.py",
    "./syn_512x512.py",
    "./bdd100k_512x512.py",
    "./cityscapes_512x512.py",
    "./mapillary_512x512.py",
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=False,
    pin_memory=False,
    sampler=dict(type="InfiniteSampler", shuffle=True),
    dataset=dict(
        type="ConcatDataset",
        datasets=[
            {{_base_.train_gta}},
            {{_base_.train_syn}}
        ],
    ),
)
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=False,
    sampler=dict(type="DefaultSampler", shuffle=False),
    dataset=dict(
        type="ConcatDataset",
        datasets=[
            {{_base_.val_cityscapes}},
            {{_base_.val_bdd}},
            {{_base_.val_mapillary}},
        ],
    ),
)
test_dataloader = val_dataloader
val_evaluator = dict(
    type="DGIoUMetric", iou_metrics=["mIoU"], dataset_keys=["citys", "map", "bdd"]
)
test_evaluator=val_evaluator
```

**Comment by w1oves** [comment]
This config seems right. Please provide generated entire config. It can be found at corresponded work_dirs.

**Comment by seabearlmx** [comment]
[config.zip](https://github.com/w1oves/Rein/files/14912692/config.zip)

**Comment by w1oves** [comment]
The error occurs because in `ConcatDataset`, you should not set the `pipeline` argument. The pipeline for different datasets should be created or updated individually for each dataset. From the provided config, it's unclear where you added this error argument. You should double-check it.

**Comment by seabearlmx** [comment]
I comment the code ``` train_dataloader = dict(batch_size=4, dataset=dict(pipeline=train_pipeline))``` in the [Rein](https://github.com/w1oves/Rein/tree/train)/[configs](https://github.com/w1oves/Rein/tree/train/configs)/[dinov2](https://github.com/w1oves/Rein/tree/train/configs/dinov2)
/[rein_dinov2_mask2former_512x512_bs1x4.py](https://github.com/w1oves/Rein/blob/train/configs/dinov2/rein_dinov2_mask2former_512x512_bs1x4.py), the multi-source setting is work well. Need you comment this code in your code?

**Comment by w1oves** [comment]
This config is only for single source. And pipeline should be added at the single dataset config. Thank you for pointing out that!
