### ISSUE TITLE
The version of xFormers

### ISSUE THREAD

**Issue by Stark320** [w1oves/Rein#27]
I encounter this issue when using dinov2 for training:

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1)
    Python  3.8.16 (you have 3.8.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)

Could you tell me how to resolve it? Thanks a lot.

**Comment by w1oves** [comment]
My version of xFormers is 0.0.20.

**Comment by w1oves** [comment]
My version of Python is 3.8.16, version of cuda is 11.7, and version of Pytorch is 2.0.1.

**Comment by Unqua** [comment]
Hi, I solved this problem by updating PyTorch to 2.2.0 and reinstall xformers by `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118`

**Comment by w1oves** [comment]
Congratulations.
