### ISSUE TITLE
How to combine rein and resnet or convnext?

### ISSUE THREAD

**Issue by yangyuya** [w1oves/Rein#28]
Hello，

I notice that there are reins_resnet.py and reins_convnext.py in the code, but threre is no config file for them.  If I want to use rein in a resnet structure, how should I set the **patch_size** and **zero_mlp_delta_f** parameters, and do they matter much to the result？

Looking forward to your reply!

**Comment by w1oves** [comment]
I will update this part of code in this week.

**Comment by w1oves** [comment]
The configs for resnet and convnext have been updated in the latest version.
