### ISSUE TITLE
How to use SAM as Backbone?

### ISSUE THREAD

**Issue by jasonbourne1212** [w1oves/Rein#29]
Thank you for your excellent work!  
        Could you provide relative code for Backbone of SAM? 
Thanks a lot!

**Comment by w1oves** [comment]
OK! I am sorry that it will take some times.

**Comment by w1oves** [comment]
I have uploaded the relevant code for the SAM Backbone. The weights and config will be uploaded between May 6 and May 15.

**Comment by jasonbourne1212** [comment]
thank you very much!

**Comment by w1oves** [comment]
I have uploaded the full code for the SAM Backbone. Pre-training weight, config, log and checkpoints can be found in the Readme.md. Before using it, you should convert SAM pre-training weight by `tools/convert_models/convert_sam.py`.

**Comment by w1oves** [comment]
Please note that the code for the SAM Backbone has been updated in the latest version. I recommend pulling the entire project to ensure you have the most current updates.

**Comment by jasonbourne1212** [comment]
OK! Thank You.
