### ISSUE TITLE
checkpoint release for "dinov2_rein_and_head.pth

### ISSUE THREAD

**Issue by ByungJu-Woo** [w1oves/Rein#3]
Hi, Thank you for your great work!

I'd like to experiment with your demo, but it looks like the checkpoint is less released.
There is checkpoint for dinov2 backbone, however not for rein and its head. (i.e.,dinov2_rein_and_head.pth)
I would like to request that you finish releasing the checkpoint.

Thanks a lot !

**Comment by w1oves** [comment]
Thank you for your interest in my work! I apologize for omitting the `checkpoints` folder when uploading to Github. Fortunately, you pointed out this oversight, and I have now uploaded this folder to the repository. It includes `dinov2_rein_and_head.pth`. The `dinov2_vitl14_pretrain.pth` file needs to be downloaded from [here](https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_pretrain.pth). If this work is helpful to you, please give it a star!

**Comment by ByungJu-Woo** [comment]
Thank you for your very quick response !
