### ISSUE TITLE
Create model with input size of 128x128

### ISSUE THREAD

**Issue by xXCoffeeColaXc** [w1oves/Rein#30]
Hello!

Can I convert the model to be able to pass through images with 128 x 128 dim ? After converting with your script, run inference with this converted model. I guess I would have to change the config file as well, but it is possible ? 

Thanks

**Comment by w1oves** [comment]
### Steps to Follow:
1. **Convert the Weight File:**
   Run the following command to convert the weight file:
   ```bash
   python tools/convert_models/convert_dinov2.py checkpoints/dinov2_vitl14_pretrain.pth checkpoints/dinov2_converted_1024x1024.pth --height 128 --width 128
   ```

2. **Update Dataset Configuration:**
   Modify the following keys in `configs.datasets`:
   - `crop_size`
   - `scale`

3. **Update Model Configuration:**
   Adjust these key arguments in `configs.models`:
   - `crop_size`
   - `img_size`
   - `test_cfg.crop_size`
   - `test_cfg.stride`

4. **Adjust Final Configuration Scales:**
   Change the `scales` parameter in the final configurations to meet your specific requirements.

**Comment by xXCoffeeColaXc** [comment]
Thanks for the fast reply! I have troubles to run inference with the converted model. Any tips how to do it?
! python tools/generate_full_weights.py --dinov2_segmentor_path checkpoints/dinov2_segmentor.pth --backbone checkpoints/dinov2_converted_1024x1024.pth --rein_head checkpoints/dinov2_rein_and_head.pth
doesnt work for me.

The ultimate goal is to run inference on 128x128 images :/
