### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiaoxing2001** [w1oves/Rein#31]
作者你好: 我在复现代码时出现以下错误:
<img width="1172" alt="image" src="https://github.com/w1oves/Rein/assets/75522097/69ceeaf3-a08c-4c3c-a71a-8dade1cf7491">
<img width="985" alt="image" src="https://github.com/w1oves/Rein/assets/75522097/73ba866c-bc21-4cb8-b3a6-e3b64dec1f96">
就是在4400代时报错，无法读取标签，但是前面的训练迭代都没有问题，并且我的数据集设置跟代码一致，请问这是为什么呢？非常期待您的回复！

**Comment by xiaoxing2001** [comment]
已解决，数据没处理好

**Comment by w1oves** [comment]
是的，这个错误看上去是数据造成的，而不是代码。
