### ISSUE TITLE
pretrained checkpoints for CLIP with Rein not available?

### ISSUE THREAD

**Issue by klarareichard** [w1oves/Rein#32]
I cannot find any pretrained checkpoints in the checkpoints folder for CLIP with Rein. Also there is no link for this in the demo or Readme (only for dino). Could you also provide a link for a pretrained CLIP with Rein variant? Or am I missing this?

**Comment by w1oves** [comment]
I will provide this.

**Comment by klarareichard** [comment]
Thank you :). If this takes longer a checkpoint eva02_L_converted.pth would also help already.
