### ISSUE TITLE
why the total similarity is kept as 1 in the corresponding line of Si, which may lead to wrong modifications?

### ISSUE THREAD

**Issue by jj-ccc** [w1oves/Rein#36]
Hi author, nice to read such an interesting paper, I would like to ask why the total similarity is kept as 1 in the corresponding line of Si, which may lead to wrong modifications?

**Comment by jj-ccc** [comment]
![Uploading dc05810f17151ea0b89c009f8f852b7.png…]()

**Comment by w1oves** [comment]
* The application of softmax ensures that the similarity of each row sums to 1.
* Some features do not need modification, meaning they are dissimilar to every token; in such cases, it would be reasonable for the total similarity of that row to be lower.
* After removing a token, the similarity for each row can range from 0 to 1.

**Comment by whyandbecause** [comment]
您好，我同样关注到了这个问题，基于您的回复，我理解了这么处理的意图，但是我还有一个小疑问，在训练过程中是如何在Si中给不用改变的特征始终分配一个较大的值的？

**Comment by w1oves** [comment]
> 您好，我同样关注到了这个问题，基于您的回复，我理解了这么处理的意图，但是我还有一个小疑问，在训练过程中是如何在Si中给不用改变的特征始终分配一个较大的值的？

当所有其他值都较小时，根据softmax的特性，剩余的值将会相应增大。
