### ISSUE TITLE
Question about source domain performance.

### ISSUE THREAD

**Issue by weeknan** [w1oves/Rein#38]
Hi,

Thank you for your insightful work, which has provided me with valuable perspectives.

I have a question regarding the performance on the source domain, specifically the mIoU on GTAV as presented in Table 4. On the source domain, does Rein outperform other methods such as VPT and Adaptformer?

Best regards.

**Comment by w1oves** [comment]
I haven't recorded the performance for the source domain, but based on our experiments with Cityscapes, the performance of my method should be similar to that of full parameter fine-tuning.

**Comment by weeknan** [comment]
ok，thx！

**Comment by w1oves** [comment]
When trained on cityscapes, the evaluation mIoU of Rein is 84.2, and full fine-tune is 84.2, too.
