### ISSUE TITLE
mmcv version conflict

### ISSUE THREAD

**Issue by FelixCaae** [w1oves/Rein#39]
As depicted in the readme, mmcv  >=2.0.0 is recommended   However, when I try to prepare my cityscape dataset with the provided script (cityscapes.py), it comes out with an error says that mmcv.scandir is not found.
I has checked the version of mmcv and found that mmcv stop supporting this function since 2.0.0 and so there is a conflict.

**Comment by w1oves** [comment]
Thank you for pointing out that issue! Modifying mmcv to mmengine should resolve the problem. I have pushed the corrected code to GitHub.
