### ISSUE TITLE
dataloader  error 

### ISSUE THREAD

**Issue by deepalenYeager** [w1oves/Rein#40]
This is a great piece of work! However, I encountered some issues while trying to train the model using the command “python tools/train.py configs/resnet/rein_resnet50_mask2former_512x512_bs1x4.py”      ：

/home/xiaoxu/Rein/rein/models/backbones/dino_layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/xiaoxu/Rein/rein/models/backbones/dino_layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/xiaoxu/Rein/rein/models/backbones/dino_layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
Fail to import ReinsConvNeXt, if you need to use it, please install mmpretrain
Traceback (most recent call last):
  File "/home/xiaoxu/Rein/tools/train.py", line 116, in <module>
    main()
  File "/home/xiaoxu/Rein/tools/train.py", line 105, in main
    runner = Runner.from_cfg(cfg)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/xiaoxu/.conda/envs/rein/lib/python3.11/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
             ^^^^
  File "/home/xiaoxu/.conda/envs/rein/lib/python3.11/site-packages/mmengine/runner/runner.py", line 342, in __init__
    raise ValueError(
ValueError: val_dataloader, val_cfg, and val_evaluator should be either all None or not None, but got val_dataloader=None, val_cfg={'type': 'ValLoop'}, val_evaluator=None

I have confirmed that my environment configuration is as follows:

mmcv: 2.1.0
mmdet: 3.3.0
mmengine: 0.10.3
mmsegmentation: 1.2.2
Python: 3.11
PyTorch: 2.0.1
CUDA: 11.7
I am using the Cityscapes dataset.I have tried several methods to resolve this issue but have not found a solution yet. Do you have any suggestions or guidance to help solve this problem?

**Comment by w1oves** [comment]
It's confused. Can you provide generated entire configs? It should be in the work_dirs.

**Comment by deepalenYeager** [comment]
Sorry，nothing has been generated under the work_dirs directory, only the directory structure work_dirs/rein_resnet50_mask2former_512x512_bs1x4 has been created。

**Comment by w1oves** [comment]
Did you modify the _base_ part? The file configs/_base_/datasets/cityscapes_512x512.py is only used to generate the file configs/_base_/datasets/dg_citys2acdc_512x512.py. Using the former directly won't make sense.

If you want to train on Cityscapes and test on Cityscapes, I have uploaded the file configs/_base_/datasets/supervised_cityscapes_512x512.py for you. You only need to replace "../_base_/datasets/dg_gta_512x512.py" in the _base_ part with this new file.

If you want to train on Cityscapes and test on ACDC, you should use configs/_base_/datasets/dg_citys2acdc_512x512.py.

**Comment by IronmanVsThanos** [comment]
![image](https://github.com/w1oves/Rein/assets/80081631/f051e82b-0efc-4d0a-9e0a-84858c08d9ea)
![image](https://github.com/w1oves/Rein/assets/80081631/2c0b3ec4-468b-47ef-8db6-de2f775baceb)
 当我按照您上述操作后，出现了上述问题。
下面是我的数据集结构
![image](https://github.com/w1oves/Rein/assets/80081631/b0e2e805-e570-4cbd-b350-849ce1905a49)

**Comment by deepalenYeager** [comment]
Thank you so much, I will try it.

**Comment by w1oves** [comment]
Sorry, i forget to add `train_dataloader` in `configs/_base_/datasets/supervsied_cityscapes_512x512.py`. I have updated this.

**Comment by IronmanVsThanos** [comment]
Thank you so much，but  where could i get the dinov2_converted.pth use /tools/converted_models/convet_dinov2?

**Comment by IronmanVsThanos** [comment]
thank u, it works.
