### ISSUE TITLE
Reproducing Table 2

### ISSUE THREAD

**Issue by helen1c** [w1oves/Rein#41]
Hi @w1oves,

Congratulations on the excellent work.

I am keen to reproduce Table 2 from your paper but have been unable to locate all the necessary configuration files. Could you please provide guidance on which scripts to run and the specific hyperparameters required? I am particularly interested in the "Freeze" and "Rein" rows.

Thank you in advance for your assistance.

**Comment by w1oves** [comment]
I will be releasing these checkpoints. Given the substantial number of checkpoints to publish, I will prioritize the release of those related to the dinov2 and clip models. It's worth noting that the checkpoint for dinov2 combined with reins has already been released. Additionally, the configurations for both frozen dinov2 and the full dinov2 have been made available.

**Comment by helen1c** [comment]
@w1oves,

Thank you for your reply.

I am specifically interested in the configurations (**not** checkpoints) for all five "freeze" models (DINOV2, CLIP, MAE, SAM, and EMA) shown in Table 5. I would like to reproduce these results on my own.

Could you let me know when you expect to publish these configurations?

Thank you!

**Comment by w1oves** [comment]
You can find frozen  dinov2 and clip config in configs/frozen_vfms. Others will be released soon.

**Comment by w1oves** [comment]
The configs for frozen SAM-H and EVA02-L have uploaded.
