### ISSUE TITLE
How Did You Choose Checkpoints?

### ISSUE THREAD

**Issue by helen1c** [w1oves/Rein#42]
Hi,

Amazing work!

I am interested in understanding how you chose checkpoints during training. For example, when training on GTA5 -> City, did you evaluate performance on City every 8000 iterations? What was the rationale for selecting 40000 iterations as your training duration?

Thank you!

**Comment by w1oves** [comment]
Training for 40,000 iterations is a common practice applied universally to all models, where we conduct testing using the checkpoint saved at the end of the 40,000 iterations. Validating every 8,000 iterations serves to monitor the correctness of the training process during its early phases, and this step is independent of the selection of the checkpoint.

**Comment by w1oves** [comment]
We primarily adhered to the iteration settings outlined in the research "RobustNet: Improving Domain Generalization in Urban-Scene Segmentation via Instance Selective Whitening" by Sungha Choi, Sanghun Jung, Huiwon Yun, Joanne T. Kim, Seungryong Kim, and Jaegul Choo, which was presented at the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR) in 2021, pages 11580-11590.
