### ISSUE TITLE
about checkpoints trained on Ctyscapes with crop size of (512,512)

### ISSUE THREAD

**Issue by tpy001** [w1oves/Rein#49]
Hi, Thank you for your great work!

I am now following your work and need to compare ours with yours on Cityscapes to BDD100k+Mapillary. However, I found that the checkpoint trained on Cityscapes uses a crop size of 1024x1024. Could you please provide the checkpoint with a crop size of 512x512 for a fair comparison?

Thanks a lot!

**Comment by w1oves** [comment]
The results of 512x512 will be slightly lower than those of 512x1024, with an mIoU of 65.43 on BDD100k, and an mIoU of 71.69 on Mapillary. I upload the corresponding config, log, and checkpoint in https://github.com/w1oves/Rein/releases/tag/Cityscapes512.

**Comment by tpy001** [comment]
Thank you so much！
