### ISSUE TITLE
checkpoints with Rein + EVA02  on GTAV -> Cityscapes

### ISSUE THREAD

**Issue by tpy001** [w1oves/Rein#51]
Hi, Thank you for your amazing work!

Do you saved the checkpoints for Rein + EVA02 backbone? I would like to test the model on another dataset.

Thank you very  much!

**Comment by w1oves** [comment]
Sorry, due to a very busy schedule recently, I won't be able to provide the requested checkpoint before next Thursday.

**Comment by w1oves** [comment]
If you are willing to wait, I will provide the checkpoint as soon as possible.

**Comment by tpy001** [comment]
Thank you for your prompt response. I will try training the model myself first. If I encounter any issues, I will reach out to you. Thank you!

**Comment by w1oves** [comment]
[This](https://github.com/w1oves/Rein/issues/33) and other issues may be helpful.

**Comment by w1oves** [comment]
I sincerely apologize for the late response! I have uploaded the config, log, and checkpoint for Rein+EVA02: https://github.com/w1oves/Rein/releases/tag/GTAV%2BEVA-L. Thank you for your support of Rein!
