### ISSUE TITLE
Discrepancy Between Training Log and Paper Results for Cityscapes -> ACDC

### ISSUE THREAD

**Issue by ysj9909** [w1oves/Rein#52]
Hello! The training log for cityscapes -> ACDC shows a performance of 73.41, but the paper mentions 77.6. Could you please explain this discrepancy? Thank you!

**Comment by w1oves** [comment]
In log, the metric is on the val set. The metrics in the paper are obtained on the test set. This is clearly stated in the paper, and you can find rein's results on acdc's official website.

**Comment by w1oves** [comment]
https://acdc.vision.ee.ethz.ch/submissions/65b6848187f1a5171cf44c34
