### ISSUE TITLE
Regarding Table 3: results on HGFormer

### ISSUE THREAD

**Issue by jnikhilreddy** [w1oves/Rein#55]
Hi,

Thanks for the great work. Can you release the config file and pretrained models for HGFormer and HGFormer-Rein used for cityscapes to ACDC results in Table 3.

**Comment by w1oves** [comment]
Hello, thank you for your support of Rein! We did not train HGFormer ourselves but directly utilized the experimental results provided in their paper, trusting their correctness. If you require related information, please refer to the HGFormer code: https://github.com/dingjiansw101/HGFormer. Furthermore, although it might be a meaningful endeavor, we have not trained HGFormer+Rein. Should you need similar experimental results, feel free to explore our DINOV2+Reins release: https://github.com/w1oves/Rein/releases/tag/Cityscapes. Our results in Table 3 are derived from this release. Once again, thank you for your attention to Rein!
