### ISSUE TITLE
The whole command for visualizing results?

### ISSUE THREAD

**Issue by Bootiap** [w1oves/Rein#56]
New to segmentation models. Just want to know the whole command for viewing my results, thank you.

**Comment by w1oves** [comment]
python tools/visualize.py /path/to/cfg /path/to/checkpoint /path/to/images --backbone /path/to/converted_backbone

**Comment by Bootiap** [comment]
After I run the command below:
python tools/visualize.py work_dirs/rein_dinov2_mask2former_512x512_bs1x4/rein_dinov2_mask2former_512x512_bs1x4.py work_dirs/rein_dinov2_mask2former_512x512_bs1x4/iter_40000.pth pic1 --backbone checkpoints/dinov2_converted.pth

NotImplementedError occurs. What may be the reason? Thank you.

**Comment by w1oves** [comment]
Thank you very much for your support of Rein! If this project or my answer is helpful to you, please **give me a star**, which is very important to me. If you have any further questions, please feel free to ask.
