### ISSUE TITLE
rein转onnx,rein转tensorrt,rein的量化

### ISSUE THREAD

**Issue by ABC1234-gitup** [w1oves/Rein#57]
我们训练完rein在对rein进行部署时,尝试了torch.onnx.export系列,mmdeploy系列,分解转换等方法,都没有转换成功,期待能给一些rein部署的思路和相关教程.

**Comment by w1oves** [comment]
Thank you very much for your support of Rein! If this project or my answer is helpful to you, please **give me a star**, which is very important to me. If you have any further questions, please feel free to ask.
