### ISSUE TITLE
About the 'scale_init' parameter setting in Rein module

### ISSUE THREAD

**Issue by GTYuantt** [w1oves/Rein#58]
Hi, thanks to the interesting work! 
I noticed that the 'scale_init' parameter in Rein module is set to 0.001 and not changed for all your experiments. But the performance is fall down severely when I tried to set a little bigger number (e.g. 0.01). I'm confused that the delta_f produced by rein module for each ViT backbone layer output is approximately 0 when multiply a very small number (0.001). 
Do you have any insight on it, and why a little bigger number doesn't work (0.01)?

**Comment by w1oves** [comment]
In the early stages of learning, the output of Rein is noisy, so it is necessary to set a smaller scale_init. In the code, the value of scale is learnable, and 0.001 is just an initial value. In fact, 0.001 is already a relatively large value. You can refer to the descriptions in the two articles on LoRA and AdaptFormer, where they both use smaller zero initializations in similar places:

LoRA: We use a random Gaussian initialization for A and zero for B, so ∆W = BA is zero at the beginning of training.

AdaptFormer: Initialization of AdaptFormer. For the original networks, we directly load the weights pre-trained on the upstream tasks and keep them frozen/untouched during the fine-tuning process. For the newly added modules, the weights of down-projection layers are initialized with Kaiming Normal [44], while the biases of the additional networks and the weights of the up-projection layers are configured with zero initialization. The reason for the zero initialization of other layers is that in this way, the initial newly added parameters are initialized such that the new function resembles the original one at the start of the fine-tuning stage. We empirically found that if the initialization deviates too far from the identity function, the model is not stable to train.
