### ISSUE TITLE
How to visualize video and save results?

### ISSUE THREAD

**Issue by Bootiap** [w1oves/Rein#60]
I trained the model with my own dataset, how do I visualize my results of a video? 
Also, is there a way to make my results being overlayed with the original picture or the video? Thank you.

**Comment by w1oves** [comment]
I will write an appropriate script for you. If it's convenient, I hope you can mention rein in the public webpage or article where you use the video. Thank you for your support!

**Comment by w1oves** [comment]
I have uploaded `inference_video.py` in tools

**Comment by w1oves** [comment]
Thank you very much for your support of Rein! If this project or my answer is helpful to you, please give me a star, which is very important to me. If you have any further questions, please feel free to ask.

**Comment by Bootiap** [comment]
Hello, I encountered an error while visualizing video results, below is the error:
KeyError: 'ReinsDinoVisionTransformer is not in the mmseg::model registry. Please check whether the value of `ReinsDinoVisionTransformer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

I found 'ReinsDinoVisionTransformer' in the reins_dinov2.py file, do I need to put the model into the mmseg registry.py file? If so, how do I manage to do that? Thank you very much.

**Comment by w1oves** [comment]
I have updated inference_video.py and added `import rein` to solve this problem. If you find my code helpful, I'd appreciate it if you could give me a star!
