### ISSUE TITLE
Size Mismatch Error When loading  weights iter_40000.pth  with eva02 backbone

### ISSUE THREAD

**Issue by fengwen777** [w1oves/Rein#61]
Thanks for your excellent work.

During the training phase, the model runs without errors, even though there are warnings regarding missing parameters in the checkpoint. However, when I switch to testing mode, I encounter a size mismatch error related to some of the pretrained parameters.

Below is the error log:

> Loads checkpoint by local backend from path: work_dirs/rein_eva02-L_mask2former_my/iter_40000.pth
Loads checkpoint by local backend from path: checkpoints/eva02_L_pt_m38m_p14to16.pt
The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.module, backbone.buffer_names, backbone.optimizer, backbone.param_shapes, backbone.lr_scheduler, backbone.sparse_tensor_module_names, backbone.skipped_steps, backbone.global_steps, backbone.global_samples, backbone.dp_world_size, backbone.mp_world_size, backbone.ds_config, backbone.ds_version, backbone.epoch, backbone.model

missing keys in source state_dict: backbone.cls_token, backbone.pos_embed, backbone.patch_embed.proj.weight, backbone.patch_embed.proj.bias, backbone.rope.freqs_cos, backbone.rope.freqs_sin, backbone.blocks.0.norm1.weight, backbone.blocks.0.norm1.bias, backbone.blocks.0.attn.q_bias, backbone.blocks.0.attn.v_bias, backbone.blocks.0.attn.q_proj.weight, backbone.blocks.0.attn.k_proj.weight, backbone.blocks.0.attn.v_proj.weight, backbone.blocks.0.attn.proj.weight, backbone.blocks.0.attn.proj.bias, backbone.blocks.0.attn.rope.freqs_cos, backbone.blocks.0.attn.rope.freqs_sin, backbone.blocks.0.norm2.weight, backbone.blocks.0.norm2.bias, backbone.blocks.0.mlp.w1.weight, backbone.blocks.0.mlp.w1.bias, backbone.blocks.0.mlp.w2.weight, backbone.blocks.0.mlp.w2.bias, backbone.blocks.0.mlp.ffn_ln.weight, backbone.blocks.0.mlp.ffn_ln.bias, backbone.blocks.0.mlp.w3.weight, backbone.blocks.0.mlp.w3.bias, backbone.blocks.1.norm1.weight, backbone.blocks.1.norm1.bias, backbone.blocks.1.attn.q_bias, backbone.blocks.1.attn.v_bias, backbone.blocks.1.attn.q_proj.weight, backbone.blocks.1.attn.k_proj.weight, backbone.blocks.1.attn.v_proj.weight, backbone.blocks.1.attn.proj.weight, backbone.blocks.1.attn.proj.bias, backbone.blocks.1.attn.rope.freqs_cos, backbone.blocks.1.attn.rope.freqs_sin, backbone.blocks.1.norm2.weight, backbone.blocks.1.norm2.bias, backbone.blocks.1.mlp.w1.weight, backbone.blocks.1.mlp.w1.bias, backbone.blocks.1.mlp.w2.weight, backbone.blocks.1.mlp.w2.bias, backbone.blocks.1.mlp.ffn_ln.weight, backbone.blocks.1.mlp.ffn_ln.bias, backbone.blocks.1.mlp.w3.weight, backbone.blocks.1.mlp.w3.bias, backbone.blocks.2.norm1.weight, backbone.blocks.2.norm1.bias, backbone.blocks.2.attn.q_bias, backbone.blocks.2.attn.v_bias, backbone.blocks.2.attn.q_proj.weight, backbone.blocks.2.attn.k_proj.weight, backbone.blocks.2.attn.v_proj.weight, backbone.blocks.2.attn.proj.weight, backbone.blocks.2.attn.proj.bias, backbone.blocks.2.attn.rope.freqs_cos, backbone.blocks.2.attn.rope.freqs_sin, backbone.blocks.2.norm2.weight, backbone.blocks.2.norm2.bias, backbone.blocks.2.mlp.w1.weight, backbone.blocks.2.mlp.w1.bias, backbone.blocks.2.mlp.w2.weight, backbone.blocks.2.mlp.w2.bias, backbone.blocks.2.mlp.ffn_ln.weight, backbone.blocks.2.mlp.ffn_ln.bias, backbone.blocks.2.mlp.w3.weight, backbone.blocks.2.mlp.w3.bias, backbone.blocks.3.norm1.weight, backbone.blocks.3.norm1.bias, backbone.blocks.3.attn.q_bias, backbone.blocks.3.attn.v_bias, backbone.blocks.3.attn.q_proj.weight, backbone.blocks.3.attn.k_proj.weight, backbone.blocks.3.attn.v_proj.weight, backbone.blocks.3.attn.proj.weight, backbone.blocks.3.attn.proj.bias, backbone.blocks.3.attn.rope.freqs_cos, backbone.blocks.3.attn.rope.freqs_sin, backbone.blocks.3.norm2.weight, backbone.blocks.3.norm2.bias, backbone.blocks.3.mlp.w1.weight, backbone.blocks.3.mlp.w1.bias, backbone.blocks.3.mlp.w2.weight, backbone.blocks.3.mlp.w2.bias, backbone.blocks.3.mlp.ffn_ln.weight, backbone.blocks.3.mlp.ffn_ln.bias, backbone.blocks.3.mlp.w3.weight, backbone.blocks.3.mlp.w3.bias, backbone.blocks.4.norm1.weight, backbone.blocks.4.norm1.bias, backbone.blocks.4.attn.q_bias, backbone.blocks.4.attn.v_bias, backbone.blocks.4.attn.q_proj.weight, backbone.blocks.4.attn.k_proj.weight, backbone.blocks.4.attn.v_proj.weight, backbone.blocks.4.attn.proj.weight, backbone.blocks.4.attn.proj.bias, backbone.blocks.4.attn.rope.freqs_cos, backbone.blocks.4.attn.rope.freqs_sin, backbone.blocks.4.norm2.weight, backbone.blocks.4.norm2.bias, backbone.blocks.4.mlp.w1.weight, backbone.blocks.4.mlp.w1.bias, backbone.blocks.4.mlp.w2.weight, backbone.blocks.4.mlp.w2.bias, backbone.blocks.4.mlp.ffn_ln.weight, backbone.blocks.4.mlp.ffn_ln.bias, backbone.blocks.4.mlp.w3.weight, backbone.blocks.4.mlp.w3.bias, backbone.blocks.5.norm1.weight, backbone.blocks.5.norm1.bias, backbone.blocks.5.attn.q_bias, backbone.blocks.5.attn.v_bias, backbone.blocks.5.attn.q_proj.weight, backbone.blocks.5.attn.k_proj.weight, backbone.blocks.5.attn.v_proj.weight, backbone.blocks.5.attn.proj.weight, backbone.blocks.5.attn.proj.bias, backbone.blocks.5.attn.rope.freqs_cos, backbone.blocks.5.attn.rope.freqs_sin, backbone.blocks.5.norm2.weight, backbone.blocks.5.norm2.bias, backbone.blocks.5.mlp.w1.weight, backbone.blocks.5.mlp.w1.bias, backbone.blocks.5.mlp.w2.weight, backbone.blocks.5.mlp.w2.bias, backbone.blocks.5.mlp.ffn_ln.weight, backbone.blocks.5.mlp.ffn_ln.bias, backbone.blocks.5.mlp.w3.weight, backbone.blocks.5.mlp.w3.bias, backbone.blocks.6.norm1.weight, backbone.blocks.6.norm1.bias, backbone.blocks.6.attn.q_bias, backbone.blocks.6.attn.v_bias, backbone.blocks.6.attn.q_proj.weight, backbone.blocks.6.attn.k_proj.weight, backbone.blocks.6.attn.v_proj.weight, backbone.blocks.6.attn.proj.weight, backbone.blocks.6.attn.proj.bias, backbone.blocks.6.attn.rope.freqs_cos, backbone.blocks.6.attn.rope.freqs_sin, backbone.blocks.6.norm2.weight, backbone.blocks.6.norm2.bias, backbone.blocks.6.mlp.w1.weight, backbone.blocks.6.mlp.w1.bias, backbone.blocks.6.mlp.w2.weight, backbone.blocks.6.mlp.w2.bias, backbone.blocks.6.mlp.ffn_ln.weight, backbone.blocks.6.mlp.ffn_ln.bias, backbone.blocks.6.mlp.w3.weight, backbone.blocks.6.mlp.w3.bias, backbone.blocks.7.norm1.weight, backbone.blocks.7.norm1.bias, backbone.blocks.7.attn.q_bias, backbone.blocks.7.attn.v_bias, backbone.blocks.7.attn.q_proj.weight, backbone.blocks.7.attn.k_proj.weight, backbone.blocks.7.attn.v_proj.weight, backbone.blocks.7.attn.proj.weight, backbone.blocks.7.attn.proj.bias, backbone.blocks.7.attn.rope.freqs_cos, backbone.blocks.7.attn.rope.freqs_sin, backbone.blocks.7.norm2.weight, backbone.blocks.7.norm2.bias, backbone.blocks.7.mlp.w1.weight, backbone.blocks.7.mlp.w1.bias, backbone.blocks.7.mlp.w2.weight, backbone.blocks.7.mlp.w2.bias, backbone.blocks.7.mlp.ffn_ln.weight, backbone.blocks.7.mlp.ffn_ln.bias, backbone.blocks.7.mlp.w3.weight, backbone.blocks.7.mlp.w3.bias, backbone.blocks.8.norm1.weight, backbone.blocks.8.norm1.bias, backbone.blocks.8.attn.q_bias, backbone.blocks.8.attn.v_bias, backbone.blocks.8.attn.q_proj.weight, backbone.blocks.8.attn.k_proj.weight, backbone.blocks.8.attn.v_proj.weight, backbone.blocks.8.attn.proj.weight, backbone.blocks.8.attn.proj.bias, backbone.blocks.8.attn.rope.freqs_cos, backbone.blocks.8.attn.rope.freqs_sin, backbone.blocks.8.norm2.weight, backbone.blocks.8.norm2.bias, backbone.blocks.8.mlp.w1.weight, backbone.blocks.8.mlp.w1.bias, backbone.blocks.8.mlp.w2.weight, backbone.blocks.8.mlp.w2.bias, backbone.blocks.8.mlp.ffn_ln.weight, backbone.blocks.8.mlp.ffn_ln.bias, backbone.blocks.8.mlp.w3.weight, backbone.blocks.8.mlp.w3.bias, backbone.blocks.9.norm1.weight, backbone.blocks.9.norm1.bias, backbone.blocks.9.attn.q_bias, backbone.blocks.9.attn.v_bias, backbone.blocks.9.attn.q_proj.weight, backbone.blocks.9.attn.k_proj.weight, backbone.blocks.9.attn.v_proj.weight, backbone.blocks.9.attn.proj.weight, backbone.blocks.9.attn.proj.bias, backbone.blocks.9.attn.rope.freqs_cos, backbone.blocks.9.attn.rope.freqs_sin, backbone.blocks.9.norm2.weight, backbone.blocks.9.norm2.bias, backbone.blocks.9.mlp.w1.weight, backbone.blocks.9.mlp.w1.bias, backbone.blocks.9.mlp.w2.weight, backbone.blocks.9.mlp.w2.bias, backbone.blocks.9.mlp.ffn_ln.weight, backbone.blocks.9.mlp.ffn_ln.bias, backbone.blocks.9.mlp.w3.weight, backbone.blocks.9.mlp.w3.bias, backbone.blocks.10.norm1.weight, backbone.blocks.10.norm1.bias, backbone.blocks.10.attn.q_bias, backbone.blocks.10.attn.v_bias, backbone.blocks.10.attn.q_proj.weight, backbone.blocks.10.attn.k_proj.weight, backbone.blocks.10.attn.v_proj.weight, backbone.blocks.10.attn.proj.weight, backbone.blocks.10.attn.proj.bias, backbone.blocks.10.attn.rope.freqs_cos, backbone.blocks.10.attn.rope.freqs_sin, backbone.blocks.10.norm2.weight, backbone.blocks.10.norm2.bias, backbone.blocks.10.mlp.w1.weight, backbone.blocks.10.mlp.w1.bias, backbone.blocks.10.mlp.w2.weight, backbone.blocks.10.mlp.w2.bias, backbone.blocks.10.mlp.ffn_ln.weight, backbone.blocks.10.mlp.ffn_ln.bias, backbone.blocks.10.mlp.w3.weight, backbone.blocks.10.mlp.w3.bias, backbone.blocks.11.norm1.weight, backbone.blocks.11.norm1.bias, backbone.blocks.11.attn.q_bias, backbone.blocks.11.attn.v_bias, backbone.blocks.11.attn.q_proj.weight, backbone.blocks.11.attn.k_proj.weight, backbone.blocks.11.attn.v_proj.weight, backbone.blocks.11.attn.proj.weight, backbone.blocks.11.attn.proj.bias, backbone.blocks.11.attn.rope.freqs_cos, backbone.blocks.11.attn.rope.freqs_sin, backbone.blocks.11.norm2.weight, backbone.blocks.11.norm2.bias, backbone.blocks.11.mlp.w1.weight, backbone.blocks.11.mlp.w1.bias, backbone.blocks.11.mlp.w2.weight, backbone.blocks.11.mlp.w2.bias, backbone.blocks.11.mlp.ffn_ln.weight, backbone.blocks.11.mlp.ffn_ln.bias, backbone.blocks.11.mlp.w3.weight, backbone.blocks.11.mlp.w3.bias, backbone.blocks.12.norm1.weight, backbone.blocks.12.norm1.bias, backbone.blocks.12.attn.q_bias, backbone.blocks.12.attn.v_bias, backbone.blocks.12.attn.q_proj.weight, backbone.blocks.12.attn.k_proj.weight, backbone.blocks.12.attn.v_proj.weight, backbone.blocks.12.attn.proj.weight, backbone.blocks.12.attn.proj.bias, backbone.blocks.12.attn.rope.freqs_cos, backbone.blocks.12.attn.rope.freqs_sin, backbone.blocks.12.norm2.weight, backbone.blocks.12.norm2.bias, backbone.blocks.12.mlp.w1.weight, backbone.blocks.12.mlp.w1.bias, backbone.blocks.12.mlp.w2.weight, backbone.blocks.12.mlp.w2.bias, backbone.blocks.12.mlp.ffn_ln.weight, backbone.blocks.12.mlp.ffn_ln.bias, backbone.blocks.12.mlp.w3.weight, backbone.blocks.12.mlp.w3.bias, backbone.blocks.13.norm1.weight, backbone.blocks.13.norm1.bias, backbone.blocks.13.attn.q_bias, backbone.blocks.13.attn.v_bias, backbone.blocks.13.attn.q_proj.weight, backbone.blocks.13.attn.k_proj.weight, backbone.blocks.13.attn.v_proj.weight, backbone.blocks.13.attn.proj.weight, backbone.blocks.13.attn.proj.bias, backbone.blocks.13.attn.rope.freqs_cos, backbone.blocks.13.attn.rope.freqs_sin, backbone.blocks.13.norm2.weight, backbone.blocks.13.norm2.bias, backbone.blocks.13.mlp.w1.weight, backbone.blocks.13.mlp.w1.bias, backbone.blocks.13.mlp.w2.weight, backbone.blocks.13.mlp.w2.bias, backbone.blocks.13.mlp.ffn_ln.weight, backbone.blocks.13.mlp.ffn_ln.bias, backbone.blocks.13.mlp.w3.weight, backbone.blocks.13.mlp.w3.bias, backbone.blocks.14.norm1.weight, backbone.blocks.14.norm1.bias, backbone.blocks.14.attn.q_bias, backbone.blocks.14.attn.v_bias, backbone.blocks.14.attn.q_proj.weight, backbone.blocks.14.attn.k_proj.weight, backbone.blocks.14.attn.v_proj.weight, backbone.blocks.14.attn.proj.weight, backbone.blocks.14.attn.proj.bias, backbone.blocks.14.attn.rope.freqs_cos, backbone.blocks.14.attn.rope.freqs_sin, backbone.blocks.14.norm2.weight, backbone.blocks.14.norm2.bias, backbone.blocks.14.mlp.w1.weight, backbone.blocks.14.mlp.w1.bias, backbone.blocks.14.mlp.w2.weight, backbone.blocks.14.mlp.w2.bias, backbone.blocks.14.mlp.ffn_ln.weight, backbone.blocks.14.mlp.ffn_ln.bias, backbone.blocks.14.mlp.w3.weight, backbone.blocks.14.mlp.w3.bias, backbone.blocks.15.norm1.weight, backbone.blocks.15.norm1.bias, backbone.blocks.15.attn.q_bias, backbone.blocks.15.attn.v_bias, backbone.blocks.15.attn.q_proj.weight, backbone.blocks.15.attn.k_proj.weight, backbone.blocks.15.attn.v_proj.weight, backbone.blocks.15.attn.proj.weight, backbone.blocks.15.attn.proj.bias, backbone.blocks.15.attn.rope.freqs_cos, backbone.blocks.15.attn.rope.freqs_sin, backbone.blocks.15.norm2.weight, backbone.blocks.15.norm2.bias, backbone.blocks.15.mlp.w1.weight, backbone.blocks.15.mlp.w1.bias, backbone.blocks.15.mlp.w2.weight, backbone.blocks.15.mlp.w2.bias, backbone.blocks.15.mlp.ffn_ln.weight, backbone.blocks.15.mlp.ffn_ln.bias, backbone.blocks.15.mlp.w3.weight, backbone.blocks.15.mlp.w3.bias, backbone.blocks.16.norm1.weight, backbone.blocks.16.norm1.bias, backbone.blocks.16.attn.q_bias, backbone.blocks.16.attn.v_bias, backbone.blocks.16.attn.q_proj.weight, backbone.blocks.16.attn.k_proj.weight, backbone.blocks.16.attn.v_proj.weight, backbone.blocks.16.attn.proj.weight, backbone.blocks.16.attn.proj.bias, backbone.blocks.16.attn.rope.freqs_cos, backbone.blocks.16.attn.rope.freqs_sin, backbone.blocks.16.norm2.weight, backbone.blocks.16.norm2.bias, backbone.blocks.16.mlp.w1.weight, backbone.blocks.16.mlp.w1.bias, backbone.blocks.16.mlp.w2.weight, backbone.blocks.16.mlp.w2.bias, backbone.blocks.16.mlp.ffn_ln.weight, backbone.blocks.16.mlp.ffn_ln.bias, backbone.blocks.16.mlp.w3.weight, backbone.blocks.16.mlp.w3.bias, backbone.blocks.17.norm1.weight, backbone.blocks.17.norm1.bias, backbone.blocks.17.attn.q_bias, backbone.blocks.17.attn.v_bias, backbone.blocks.17.attn.q_proj.weight, backbone.blocks.17.attn.k_proj.weight, backbone.blocks.17.attn.v_proj.weight, backbone.blocks.17.attn.proj.weight, backbone.blocks.17.attn.proj.bias, backbone.blocks.17.attn.rope.freqs_cos, backbone.blocks.17.attn.rope.freqs_sin, backbone.blocks.17.norm2.weight, backbone.blocks.17.norm2.bias, backbone.blocks.17.mlp.w1.weight, backbone.blocks.17.mlp.w1.bias, backbone.blocks.17.mlp.w2.weight, backbone.blocks.17.mlp.w2.bias, backbone.blocks.17.mlp.ffn_ln.weight, backbone.blocks.17.mlp.ffn_ln.bias, backbone.blocks.17.mlp.w3.weight, backbone.blocks.17.mlp.w3.bias, backbone.blocks.18.norm1.weight, backbone.blocks.18.norm1.bias, backbone.blocks.18.attn.q_bias, backbone.blocks.18.attn.v_bias, backbone.blocks.18.attn.q_proj.weight, backbone.blocks.18.attn.k_proj.weight, backbone.blocks.18.attn.v_proj.weight, backbone.blocks.18.attn.proj.weight, backbone.blocks.18.attn.proj.bias, backbone.blocks.18.attn.rope.freqs_cos, backbone.blocks.18.attn.rope.freqs_sin, backbone.blocks.18.norm2.weight, backbone.blocks.18.norm2.bias, backbone.blocks.18.mlp.w1.weight, backbone.blocks.18.mlp.w1.bias, backbone.blocks.18.mlp.w2.weight, backbone.blocks.18.mlp.w2.bias, backbone.blocks.18.mlp.ffn_ln.weight, backbone.blocks.18.mlp.ffn_ln.bias, backbone.blocks.18.mlp.w3.weight, backbone.blocks.18.mlp.w3.bias, backbone.blocks.19.norm1.weight, backbone.blocks.19.norm1.bias, backbone.blocks.19.attn.q_bias, backbone.blocks.19.attn.v_bias, backbone.blocks.19.attn.q_proj.weight, backbone.blocks.19.attn.k_proj.weight, backbone.blocks.19.attn.v_proj.weight, backbone.blocks.19.attn.proj.weight, backbone.blocks.19.attn.proj.bias, backbone.blocks.19.attn.rope.freqs_cos, backbone.blocks.19.attn.rope.freqs_sin, backbone.blocks.19.norm2.weight, backbone.blocks.19.norm2.bias, backbone.blocks.19.mlp.w1.weight, backbone.blocks.19.mlp.w1.bias, backbone.blocks.19.mlp.w2.weight, backbone.blocks.19.mlp.w2.bias, backbone.blocks.19.mlp.ffn_ln.weight, backbone.blocks.19.mlp.ffn_ln.bias, backbone.blocks.19.mlp.w3.weight, backbone.blocks.19.mlp.w3.bias, backbone.blocks.20.norm1.weight, backbone.blocks.20.norm1.bias, backbone.blocks.20.attn.q_bias, backbone.blocks.20.attn.v_bias, backbone.blocks.20.attn.q_proj.weight, backbone.blocks.20.attn.k_proj.weight, backbone.blocks.20.attn.v_proj.weight, backbone.blocks.20.attn.proj.weight, backbone.blocks.20.attn.proj.bias, backbone.blocks.20.attn.rope.freqs_cos, backbone.blocks.20.attn.rope.freqs_sin, backbone.blocks.20.norm2.weight, backbone.blocks.20.norm2.bias, backbone.blocks.20.mlp.w1.weight, backbone.blocks.20.mlp.w1.bias, backbone.blocks.20.mlp.w2.weight, backbone.blocks.20.mlp.w2.bias, backbone.blocks.20.mlp.ffn_ln.weight, backbone.blocks.20.mlp.ffn_ln.bias, backbone.blocks.20.mlp.w3.weight, backbone.blocks.20.mlp.w3.bias, backbone.blocks.21.norm1.weight, backbone.blocks.21.norm1.bias, backbone.blocks.21.attn.q_bias, backbone.blocks.21.attn.v_bias, backbone.blocks.21.attn.q_proj.weight, backbone.blocks.21.attn.k_proj.weight, backbone.blocks.21.attn.v_proj.weight, backbone.blocks.21.attn.proj.weight, backbone.blocks.21.attn.proj.bias, backbone.blocks.21.attn.rope.freqs_cos, backbone.blocks.21.attn.rope.freqs_sin, backbone.blocks.21.norm2.weight, backbone.blocks.21.norm2.bias, backbone.blocks.21.mlp.w1.weight, backbone.blocks.21.mlp.w1.bias, backbone.blocks.21.mlp.w2.weight, backbone.blocks.21.mlp.w2.bias, backbone.blocks.21.mlp.ffn_ln.weight, backbone.blocks.21.mlp.ffn_ln.bias, backbone.blocks.21.mlp.w3.weight, backbone.blocks.21.mlp.w3.bias, backbone.blocks.22.norm1.weight, backbone.blocks.22.norm1.bias, backbone.blocks.22.attn.q_bias, backbone.blocks.22.attn.v_bias, backbone.blocks.22.attn.q_proj.weight, backbone.blocks.22.attn.k_proj.weight, backbone.blocks.22.attn.v_proj.weight, backbone.blocks.22.attn.proj.weight, backbone.blocks.22.attn.proj.bias, backbone.blocks.22.attn.rope.freqs_cos, backbone.blocks.22.attn.rope.freqs_sin, backbone.blocks.22.norm2.weight, backbone.blocks.22.norm2.bias, backbone.blocks.22.mlp.w1.weight, backbone.blocks.22.mlp.w1.bias, backbone.blocks.22.mlp.w2.weight, backbone.blocks.22.mlp.w2.bias, backbone.blocks.22.mlp.ffn_ln.weight, backbone.blocks.22.mlp.ffn_ln.bias, backbone.blocks.22.mlp.w3.weight, backbone.blocks.22.mlp.w3.bias, backbone.blocks.23.norm1.weight, backbone.blocks.23.norm1.bias, backbone.blocks.23.attn.q_bias, backbone.blocks.23.attn.v_bias, backbone.blocks.23.attn.q_proj.weight, backbone.blocks.23.attn.k_proj.weight, backbone.blocks.23.attn.v_proj.weight, backbone.blocks.23.attn.proj.weight, backbone.blocks.23.attn.proj.bias, backbone.blocks.23.attn.rope.freqs_cos, backbone.blocks.23.attn.rope.freqs_sin, backbone.blocks.23.norm2.weight, backbone.blocks.23.norm2.bias, backbone.blocks.23.mlp.w1.weight, backbone.blocks.23.mlp.w1.bias, backbone.blocks.23.mlp.w2.weight, backbone.blocks.23.mlp.w2.bias, backbone.blocks.23.mlp.ffn_ln.weight, backbone.blocks.23.mlp.ffn_ln.bias, backbone.blocks.23.mlp.w3.weight, backbone.blocks.23.mlp.w3.bias

**Comment by w1oves** [comment]
This seems to be due to one of the two weights, rein_eva02-L_mask2former_my/iter_40000.pth or checkpoints/eva02_L_pt_m38m_p14to16.pt, being incorrect. You can use `torch.load` to read the weight, check if the corresponding `.keys()` are correct, and make appropriate modifications, `torch.save` the modified weight.

**Comment by w1oves** [comment]
Thank you very much for your support of Rein! If this project or my answer is helpful to you, please give me a star, which is very important to me. If you have any further questions, please feel free to ask
