### ISSUE TITLE
运行demo得到的结果有误

### ISSUE THREAD

**Issue by kevin-xiaoxin** [w1oves/Rein#64]
English: Hello, I encountered some problems while testing the demo and would like to ask for your advice. Thank you.
1. In the first line, should the parameter name for generating the weight file --dinov2_segmentor_path be changed to --segmentor_save_path?
2. When I execute the second statement, I am prompted with the following dimension mismatch issue, and I don't know where the error is. Please let me know.
Loads checkpoint by local backend from path: checkpoints/dinov2_segmentor.pth
The model and loaded state dict do not match exactly
size mismatch for backbone.pos_embed: copying a param with shape torch.Size([1, 1370, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1025, 1024]).
size mismatch for backbone.patch_embed.proj.weight: copying a param with shape torch.Size([1024, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([1024, 3, 16, 16]).
3. The results obtained from model inference are seriously inconsistent with those in your demo. Could you please tell me what I need to change? Below are my running results.
![Uploading Running Results.png…]()

中文：你好，我在测试demo时候遇到了点问题想请教您一下，谢谢。
1. 第一行生成权重文件的参数名称--dinov2_segmentor_path是不是需要改成--segmentor_save_path。
2. 我在执行第二条语句的时候，提示下面的维度不匹配问题，不知道是哪里出错了，麻烦您告知我一下。
Loads checkpoint by local backend from path: checkpoints/dinov2_segmentor.pth
The model and loaded state dict do not match exactly
size mismatch for backbone.pos_embed: copying a param with shape torch.Size([1, 1370, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1025, 1024]).
size mismatch for backbone.patch_embed.proj.weight: copying a param with shape torch.Size([1024, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([1024, 3, 16, 16]).
3. 经过模型推理得到的结果和您demo中的严重不符合，想请教你一下我需要改什么吗？以下是我运行的结果。
![Uploading 运行结果.png…]()

**Comment by w1oves** [comment]
English: By updating the three files `rein/utils/init_model.py`, `rein/hooks/load_backbone_hook.py`, and `demo.ipynb`, I have updated the content and running method of the `demo.ipynb` file. Now, in the first cell of `demo.ipynb`, the `convert_dinov2.py` is used to convert the pre-trained weight (kernel size=14, image_size=224x224) to weight with kernel size=16, image_size=512x512, and in the second cell, the Init_model function combines the backbone weight with our trained rein_head.pth to form the complete segmentation network weight.

中文：通过更新`rein/utils/init_model.py`,`rein/hooks/load_backbone_hook.py`, 和`demo.ipynb`三个文件，我更新了demo.ipynb文件的内容和运行方式。现在demo.ipynb在第一个cell中通过`convert_dinov2.py`将pretrain weight（kernel size=14, image_size=224x224）转换为kernel size=16, image_size=512x512的weight，并在第二个cell中的Init_model函数中将backbone weight和我们训练得到的rein_head.pth合并为完整的分割网络权重。

**Comment by w1oves** [comment]
After making the above modifications, I did not test the modified code. If you find any errors in the modified code, feel free to ask at any time! Also, if my code is useful to you, please give me a star!

**Comment by kevin-xiaoxin** [comment]
> After making the above modifications, I did not test the modified code. If you find any errors in the modified code, feel free to ask at any time! Also, if my code is useful to you, please give me a star!

感谢您的耐心解答，但是再我重新运行您更新后的代码时还存在点小问题。在运行第二个cell，执行network:nn.Module=init_model(cfg,dict(backbone='checkpoints/dinov2_vitl14_converted_k16h512w512.pth',rein_head='checkpoints/dinov2_rein_and_head.pth'),'cuda:0')时，报了expected string or bytes-like object的错误。

**Comment by kevin-xiaoxin** [comment]
> After making the above modifications, I did not test the modified code. If you find any errors in the modified code, feel free to ask at any time! Also, if my code is useful to you, please give me a star!

感谢您的回复，我更新了您提到的三个文件，可以正常运行demo程序了，但是模型推理得到的结果还是不太相符，这是我重新执行后的结果。
![Uploading 结果.png.png…]()

**Comment by w1oves** [comment]
我看不到你发的图片

**Comment by kevin-xiaoxin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w1oves/Rein"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w1oves/Rein] 运行demo得到的结果有误 (Issue #64)






我看不到你发的图片

**Comment by w1oves** [comment]
我看不到你发的图片
