### ISSUE TITLE
得到resnet训练权重后，如何对我自己采集的图片进行分割

### ISSUE THREAD

**Issue by zj010131** [w1oves/Rein#65]
作者你好，你们的工作让我受益匪浅。
我使用rein_resnet50_mask2former_512x512，batchsize为2的config进行训练，并得到了对应权重iter_160000.pth。那么我该如何使用这个权重以及config来对我自己采集的图片进行分割？

**Comment by w1oves** [comment]
你可以参考 #60, #22, and https://mmsegmentation.readthedocs.io/zh-cn/latest/user_guides/visualization.html。
