### ISSUE TITLE
Urbansyn convert dataset code 

### ISSUE THREAD

**Issue by ysj9909** [w1oves/Rein#66]
Hello! Thank you for sharing the code from your amazing research. I would like to conduct experiments on Urbansyn, and I found out that a dataset conversion code is necessary. Could I kindly ask if you could provide the convert_dataset code that you used for the Urbansyn experiments? I would greatly appreciate it. Thank you!

**Comment by w1oves** [comment]
Thank you for your support of Rein! The data organization of Urbansyn is very clear, so no special conversion is needed, and we appreciate the outstanding contributions of their authors! The only thing that needs to be done is: in Urbansyn, the void value is represented by 19, while we are used to using 255. You can use this script to modify the corresponding pixel values: `tools/convert_datasets/urbansyn.py`. If you need the config for Urbansyn, you can refer to: `configs/_base_/datasets/urbansyn_512x512.py` and `configs/_base_/datasets/urbansyn_synthia_gtav_to_citys.py`.

**Comment by ysj9909** [comment]
Thank you so much for your quick and accurate responses. Recently, I've been conducting experiments with a lot of help from the authors, and I'd love to discuss my research further. I'll be in touch soon!
