### ISSUE TITLE
mIoU for ACDC Validation Set

### ISSUE THREAD

**Issue by Busso00** [w1oves/Rein#67]
Hi Lin Chen, Wei Zhixiang, and Team,

I hope this message finds you well! I just wanted to take a moment to commend you on the fantastic results presented in your recent work. The performance metrics are impressive and it’s clear that a lot of hard work has gone into this project.

I am particularly interested in understanding more about the validation metrics, specifically the mean Intersection over Union (mIoU) on the ACDC validation set. Could you please share the mIoU value you achieved during your experiments? It would be great to have that information to better assess the model's performance on that dataset.

Thank you for your contributions to the field, and I look forward to your response!

Best regards,
Federico Bussolino

**Comment by w1oves** [comment]
Thank you for your support! I guess you might have discovered that the mIoU for the ACDC validation set is available in the following JSON file: [https://github.com/w1oves/Rein/releases/download/Cityscapes/20240120_154745.json](https://github.com/w1oves/Rein/releases/download/Cityscapes/20240120_154745.json).
