### ISSUE TITLE
自定义数据集训练

### ISSUE THREAD

**Issue by 1404561326521** [w1oves/Rein#70]
作者您好，感谢您的开源！
我按照readme在自定义数据集上复现了模型，输出结果如下图，我想知道这是正常的嘛？如果正常，这些参数表述什么含义啊？
![image](https://github.com/user-attachments/assets/3ae5f1b3-3716-48cb-b45a-ec5597b75a6f)

**Comment by w1oves** [comment]
这看起来是正常的。base_lr代表学习率，lr 代表当前学习率，eta代表剩余时间，time代表每个迭代的时间。其余代表各类损失。
