### ISSUE TITLE
Question about state_dict

### ISSUE THREAD

**Issue by LTT-5** [w1oves/Rein#75]
Hello!

Great job with the work on reins! I just started learning and have a question. 

When using custom dataset made by myself to train with the config file (i.e., rein_dinov2_mask2former_512x512_bs1x4.py), if I keep the state_dict function in reins_dinov2.py, the trained epoch_xx.pth performs very poorly when running test.py, with metrics close to zero. However, if I comment out the state_dict function, the model trained on my dataset performs well on the test. Could you let me know if I'm making any mistakes?

'''
If I comment out this code, does it mean that the entire set of model parameters is being saved? In that case, the purpose of reins (to reduce model parameters) wouldn’t be reflected. But if I don’t comment it out, I don’t get good test results. How can I resolve this？
'''
def state_dict(self, destination, prefix, keep_vars):
        state = super().state_dict(destination, prefix, keep_vars)
       keys = [k for k in state.keys() if "rein" not in k]
        for key in keys:
            state.pop(key)
            if key in destination:
                destination.pop(key)
        return state

**Comment by w1oves** [comment]
You can achieve the desired effect by commenting out that function. If you want the checkpoint to take up less disk space, use `python tools/test.py configs/dinov2/rein_dinov2_mask2former_512x512_bs1x4.py checkpoints/dinov2_rein_and_head.pth --backbone dinov2_converted.pth`. This means that during testing, you need to provide not only the path to your trained results but also the path to the backbone you loaded during training.

**Comment by LTT-5** [comment]
Great thanks for your reply! 
I got it! I will try again.
