### ISSUE TITLE
Simple_Rein as Feature Encoder

### ISSUE THREAD

**Issue by xuge-coder** [w1oves/Rein#76]
您好！请问利用Simple_Rein训练自己的数据集，下载了DINOv2的权重，提示如下问题：
RuntimeError: Error(s) in loading state_dict for ReinsDINOv2:
	Missing key(s) in state_dict: "reins.scale", "reins.learnable_tokens_a", "reins.learnable_tokens_b", "reins.mlp_token2feat.weight", "reins.mlp_token2feat.bias", "reins.mlp_delta_f.weight", "reins.mlp_delta_f.bias". 
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1297, 1024]).
另外，数据集大小不是512x512，h和w不相等，在pos_embeddings时不正确，请问这个怎么解决？是要对预训练权重进行处理吗？
谢谢！期待回复！

**Comment by w1oves** [comment]
* 我已经通过增加`strict=False`修复了Missing key(s)错误并提交。
* 对于size misatch错误，你需要使用`tools/convert_models/convert_dinov2.py`来转换预训练权重。
* 对于`h!=w`的情况，我没有进行过相关的测试，因此不能提供给你可信的代码。但我相信你可以在转换合适的预训练权重的基础上通过小幅修改代码增加这个功能。这应该不会很难。
---
* I have fixed the `Missing key(s)` error by adding `strict=False` and submitted the changes.
* For the `size mismatch` error, you need to use `tools/convert_models/convert_dinov2.py` to convert the pretrained weights.
* I haven't tested the case where `h!=w`, so I can't provide you with reliable code. However, I believe you can add this functionality with minor modifications to the code after converting the pretrained weights accordingly. It shouldn't be difficult.

**Comment by xuge-coder** [comment]
Thanks！感谢您的回复！
