### ISSUE TITLE
have you ever try synthia->C, B, M?

### ISSUE THREAD

**Issue by ByungJu-Woo** [w1oves/Rein#9]
Hello, thank you for your great work! 
Have you ever trained your Rein on "synthia to others" setting? (single-source)
I wonder the result of synthia setting for same setting with GTAV (i.e, crop size 512 x 512).
Is there official report of this setting?
Thanks a lot.

**Comment by w1oves** [comment]
I have not conducted this experiment. However, I have reported the results under the GTAV+Synthia configuration on arXiv.

**Comment by w1oves** [comment]
> Hello, thank you for your great work! Have you ever trained your Rein on "synthia to others" setting? (single-source) I wonder the result of synthia setting for same setting with GTAV (i.e, crop size 512 x 512). Is there official report of this setting? Thanks a lot.


I'm quite intrigued to know if you've experimented with this setup. How were the results?
